### ISSUE TITLE
请问如何怎么获取参数  Window Name，代码定义非常模糊

### ISSUE THREAD

**Issue by orange250** [T-Rumibul/node-native-win-utils#1]
看了案例 都没有说明 参数 Window Name 是什么，应该是窗口句柄或者窗口的title，然而 Node.js没有获取相关窗口名字的库，疑惑
感谢作者

**Comment by T-Rumibul** [comment]
Window Name = window title. It basically uses this function to retrieve a handle: https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-findwindowa. I developed this addon to use with a specific app window, so the only way is to input the title manually or use another addon, etc. Sorry if I misunderstood your question; I'm using a translator.

**Comment by orange250** [comment]
作业已收到，请利用假期充实自己，你的时间由你自己掌控
